
INSERT INTO departments (department_name)
VALUES 
("SALES"),
("ENGINEERING"),
("FINANCE"),
("LEGAL");

INSERT INTO roles (role_title, salary, department_name)
VALUES 
("SALES LEAD", 80000.00, "SALES"),
("SALES PERSON", 50000.00, "SALES"),
("LEAD ENGINEER", 100000.00, "ENGINEERING"),
("ENGINEER", 70000.00, "ENGINEERING"),
("JUNIOR ENGINEER", 60000.00, "ENGINEERING"),
("LEAD ACCOUNTANT", 70000.00, "FINANCE"),
("ACCOUNTANT", 50000.00, "FINANCE"),
("LEGAL TEAM LEAD", 100000.00, "LEGAL"),
("LAWYER", 80000.00, "LEGAL");

INSERT INTO employees (employee_first_name, employee_last_name, role_title, employee_manager)
VALUES 
("JOHN", "DOE", "LEAD ENGINEER", "NONE"),
("GABE", "MORRIS", "JUNIOR ENGINEER", "JOHN DOE"),
("TIM", "SMITH", "ACCOUNTANT", "GEOFF SMITH"),
("HANNAH", "JACKSON", "LEGAL TEAM LEAD", "NONE"),
("BOBBY", "SMITH", "LAWYER", "HANNAH JACKSON"),
("AVA", "DOE", "ENGINEER", "JOHN DOE");